use_frameworks!

platform :ios, '8.0'

target 'TBSNavigationController_Example' do
  pod 'TBSNavigationController', :path => '../'

  target 'TBSNavigationController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
